name: Configlet

on:
  push:
  pull_request:

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e # 2.0.0

    - name: Fetch configlet
      run: ./bin/fetch-configlet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint
      run: ./bin/configlet lint .
